// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB13INkh-YiIQeucslNvtEqrV_58XsC-CE',
    appId: '1:1020462080586:android:8ed9366522594c99a7bcb3',
    messagingSenderId: '1020462080586',
    projectId: 'matchmeloversapp',
    storageBucket: 'matchmeloversapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAainGYDyswAPX4TqgbhgyDv51ANbyNfcE',
    appId: '1:1020462080586:ios:37a865f83d0b17c5a7bcb3',
    messagingSenderId: '1020462080586',
    projectId: 'matchmeloversapp',
    storageBucket: 'matchmeloversapp.firebasestorage.app',
    iosBundleId: 'com.example.matchmeLover',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB13INkh-YiIQeucslNvtEqrV_58XsC-CE',
    appId: '1:1020462080586:web:8ed9366522594c99a7bcb3',
    messagingSenderId: '1020462080586',
    projectId: 'matchmeloversapp',
    authDomain: 'matchmeloversapp.firebaseapp.com',
    storageBucket: 'matchmeloversapp.firebasestorage.app',
  );
}
